# Generated by Django 4.2.17 on 2025-02-20 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyreport',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_reports_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklymilkrecord',
            name='cow_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.lactatingcow'),
        ),
        migrations.AddField(
            model_name='weeklymilkrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetjudgment',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_judgments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetjudgment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veterinarydrugs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veterinarybills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veterinarybilling',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_billing_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veterinarybilling',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vaccination', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_farmer': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uterineirrigationrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='uterine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uterineirrigationrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userretake',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.section'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='surgical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surgicalrecord',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'is_vet_officer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterhouse',
            name='assigned_to_official',
            field=models.ForeignKey(limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='slaughter_house', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterhouse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portals.tutorial'),
        ),
        migrations.AddField(
            model_name='sampleprocessing',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='processing_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleprocessing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesofmilk',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaries',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_by_name', to='portals.employees'),
        ),
        migrations.AddField(
            model_name='salaries',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portals.section'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.moderator'),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartely_reports_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregnancymonitoring',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregnancydiagnosis',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pregdiagnosis_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregnancydiagnosis',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmortemrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='postmortem_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmortemrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='noobjection_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newanimal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movementpermit',
            name='assigned_to_official',
            field=models.ForeignKey(default=1, limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movement_permit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movementpermit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlymilkrecord',
            name='cow_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.lactatingcow'),
        ),
        migrations.AddField(
            model_name='monthlymilkrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minerals',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='cow_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.lactatingcow'),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='employee_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portals.employees'),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinsurance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockincident',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='incidence_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockincident',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockexaminationrecord',
            name='assigned_to_official',
            field=models.ForeignKey(limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='examination_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockexaminationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lactatingcow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatsignmonitoring',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeds',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmconsultation',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmconsultation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycare',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycare',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='assigned_to_official',
            field=models.ForeignKey(limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='disease_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deworming',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='deworming_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deworming',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadanimal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dairyhygiene',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dairyequipment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailymilkrecord',
            name='cow_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.lactatingcow'),
        ),
        migrations.AddField(
            model_name='dailymilkrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailykill',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailykill',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailykill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='culling',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpdquestions',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portals.section'),
        ),
        migrations.AddField(
            model_name='cpdquestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpdchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='portals.cpdquestions'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portals.section'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_vet_officer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='request_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calvingrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='butcher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'is_farmer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assesment_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_farmer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archaricides',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalsale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monthlymilkrecord',
            unique_together={('cow_name', 'month')},
        ),
    ]
