# Generated by Django 4.2.17 on 2025-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasereport',
            name='livestock_category',
            field=models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Donkey', 'Donkey'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Poultry', 'Poultry'), ('None', 'None')], max_length=20),
        ),
    ]
