# Generated by Django 4.2.17 on 2025-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_alter_diseasereport_livestock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycare',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='emergencycare',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='breed',
            field=models.CharField(choices=[('Holstein', 'Holstein'), ('Jersey', 'Jersey'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Charolais', 'Charolais'), ('Limousin', 'Limousin'), ('Guernsey', 'Guernsey'), ('Ayrshire', 'Ayrshire'), ('Brown Swiss', 'Brown Swiss'), ('Shorthorn', 'Shorthorn'), ('Other', 'Other')], max_length=50),
        ),
    ]
