# Generated by Django 4.2.17 on 2025-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_remove_emergencycare_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
