# Generated by Django 4.2.17 on 2025-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_clientrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='case_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='communication_methods',
            field=models.CharField(choices=[('Audio Call', 'Audio Call'), ('Video Calls', 'Video Calls'), ('Sms', 'Sms')], default='Sms', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='photo',
            field=models.ImageField(default='dddd', upload_to='livestock_photos/'),
            preserve_default=False,
        ),
    ]
