# Generated by Django 4.2.17 on 2025-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_clientrequest_case_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='non_emergency_condition',
            field=models.CharField(blank=True, choices=[('severe_bleeding', 'Severe Bleeding'), ('dystocia', 'Dystocia'), ('bloat', 'Bloat'), ('snake bite', 'Snake Bite'), ('fracture', 'Fracture'), ('uterine prolapse', 'Uterine Prolapse'), ('choking', 'Choking'), ('milk fever', 'Milk Fever'), ('none', 'None')], max_length=50, null=True),
        ),
    ]
