# Generated by Django 4.2.17 on 2025-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_clientrequest_non_emergency_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmortemrecord',
            name='cause_of_death',
            field=models.CharField(default='strangulation', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='non_emergency_condition',
            field=models.CharField(blank=True, choices=[('Chronic Condition', 'Chronic Condition'), ('Farm Visit', 'Farm Visit'), ('None', 'None')], max_length=50, null=True),
        ),
    ]
