# Generated by Django 4.2.17 on 2025-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_postmortemrecord_cause_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmortemrecord',
            name='reg_no',
            field=models.CharField(default='sdd423', max_length=100),
            preserve_default=False,
        ),
    ]
