# Generated by Django 4.2.17 on 2025-03-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0010_postmortemrecord_reg_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='is_active',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='is_active',
            new_name='is_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portals.tutorial'),
        ),
    ]
