# Generated by Django 4.2.17 on 2025-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0011_rename_is_active_section_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='telemedicine_category',
            field=models.CharField(choices=[('Teletriage', 'Teletriage'), ('Teleconsultation', 'Teleconsultation'), ('Teleonitoring', 'Telemonitoring'), ('Teleadvice', 'Teleadvice')], default='teletriage', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vetjudgment',
            name='telemedicine_category',
            field=models.CharField(choices=[('Teletriage', 'Teletriage'), ('Teleconsultation', 'Teleconsultation'), ('Teleonitoring', 'Telemonitoring'), ('Teleadvice', 'Teleadvice')], max_length=20),
        ),
    ]
