# Generated by Django 4.2.17 on 2025-03-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0012_clientrequest_telemedicine_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='judgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='livestock_photos/'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='telemedicine_category',
            field=models.CharField(choices=[('Teletriage', 'Teletriage'), ('Teleconsultation', 'Teleconsultation'), ('Telemonitoring', 'Telemonitoring'), ('Teleadvice', 'Teleadvice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vetjudgment',
            name='telemedicine_category',
            field=models.CharField(choices=[('Teletriage', 'Teletriage'), ('Teleconsultation', 'Teleconsultation'), ('Telemonitoring', 'Telemonitoring'), ('Teleadvice', 'Teleadvice')], max_length=20),
        ),
    ]
