# Generated by Django 4.2.17 on 2025-03-05 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0013_clientrequest_judgement_alter_clientrequest_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
