# Generated by Django 4.2.17 on 2025-04-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0014_clientrequest_assigned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Neighbour', 'Neighbour'), ('Hotel', 'Hotel'), ('Cooperative', 'Cooperative')], max_length=20)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='salesofmilk',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesofmilk',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.buyer'),
        ),
    ]
