# Generated by Django 4.2.17 on 2025-04-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0015_buyer_salesofmilk_buyer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesofmilk',
            name='buyer_contact',
        ),
        migrations.RemoveField(
            model_name='salesofmilk',
            name='buyer_name',
        ),
    ]
