# Generated by Django 4.2.17 on 2025-04-07 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0016_remove_salesofmilk_buyer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='agreed_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='date_of_enrollment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='duration_of_supply',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='payment_mode',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks'), ('monthly', 'Monthly'), ('other', 'Other')], default='daily', max_length=10),
            preserve_default=False,
        ),
    ]
