# Generated by Django 4.2.17 on 2025-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0017_buyer_agreed_price_per_kg_buyer_date_of_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsale',
            name='breed',
            field=models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Poultry', 'Poultry'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='category',
            field=models.CharField(choices=[('Neighbour', 'Neighbour'), ('Hotel', 'Hotel'), ('Cooperative', 'Cooperative'), ('Institution', 'Institution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesofmilk',
            name='milk_sales_to',
            field=models.CharField(choices=[('Neighbour', 'Neighbour'), ('Hotel', 'Hotel'), ('Cooperative', 'Cooperative'), ('Institution', 'Institution')], max_length=12),
        ),
    ]
