# Generated by Django 4.2.17 on 2025-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0018_alter_animalsale_breed_alter_buyer_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_buyer', models.CharField(choices=[('Neighbour', 'Neighbour'), ('Hotel', 'Hotel'), ('Cooperative', 'Cooperative'), ('Institution', 'Institution')], max_length=20)),
                ('date_of_payment', models.DateField()),
                ('total_kg_or_litres_supplied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg_or_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_to_receive', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_received_from', models.CharField(max_length=100)),
                ('payment_received_by', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Cheque', 'Cheque')], max_length=20)),
                ('contracts', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animalsale',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Young One', 'Young One')], default='', max_length=100),
        ),
    ]
