# Generated by Django 4.2.17 on 2025-05-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0020_payments_user_alter_payment_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='price_per_kg_or_litre',
            new_name='price_per_kg',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='total_kg_or_litres_supplied',
            new_name='total_kg_supplied',
        ),
    ]
