# Generated by Django 4.2.17 on 2025-05-01 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0021_rename_price_per_kg_or_litre_payments_price_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='category_of_buyer',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_received_from',
        ),
        migrations.AddField(
            model_name='payments',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='total_amount_to_receive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
