# Generated by Django 4.2.17 on 2025-05-10 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0023_otherexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_check', models.DateField()),
                ('time_of_check', models.TimeField()),
                ('check_section', models.CharField(choices=[('healthy_status', 'Healthy Status'), ('feeds_and_feeding', 'Feeds and Feeding'), ('heat_signs', 'Heat Signs'), ('steaming_up', 'Steaming Up'), ('biosecurity_system', 'Biosecurity System'), ('milk_hygiene', 'Milk Hygiene'), ('calves_section', 'Calves Section'), ('dairy_equipment', 'Dairy Equipment'), ('farm_records', 'Farm Records'), ('pregnant_cows', 'Pregnant Cows')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('checked_by', models.CharField(choices=[('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('owner', 'Owner'), ('consultant', 'Farm Consultant')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
