# Generated by Django 4.2.17 on 2025-05-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0024_dailycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_prac', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailycheck',
            name='check_section',
            field=models.CharField(choices=[('healthy status', 'Healthy Status'), ('feeds and feeding', 'Feeds and Feeding'), ('heat signs', 'Heat Signs'), ('steaming up', 'Steaming Up'), ('biosecurity system', 'Biosecurity System'), ('milk hygiene', 'Milk Hygiene'), ('calves section', 'Calves Section'), ('dairy equipment', 'Dairy Equipment'), ('farm records', 'Farm Records'), ('pregnant cows', 'Pregnant Cows')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dailycheck',
            name='checked_by',
            field=models.CharField(choices=[('manager', 'Manager'), ('assistant manager', 'Assistant Manager'), ('owner', 'Owner'), ('consultant', 'Farm Consultant')], max_length=20),
        ),
    ]
