# Generated by Django 4.2.17 on 2025-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0025_practitioner_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatsignmonitoring',
            name='date_of_heat_monitoring',
        ),
        migrations.AddField(
            model_name='heatsignmonitoring',
            name='date_of_repeat_monitoring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heatsignmonitoring',
            name='exp_date_of_repeated_heat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
