# Generated by Django 4.2.17 on 2025-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0026_remove_heatsignmonitoring_date_of_heat_monitoring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesofmilk',
            name='number_of_cows_milked',
        ),
        migrations.RemoveField(
            model_name='salesofmilk',
            name='price_per_kg',
        ),
        migrations.RemoveField(
            model_name='salesofmilk',
            name='total_kgs_milked',
        ),
        migrations.AlterField(
            model_name='salesofmilk',
            name='balance',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
