# Generated by Django 4.2.17 on 2025-05-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0027_remove_salesofmilk_number_of_cows_milked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesofmilk',
            name='buyer',
        ),
    ]
