# Generated by Django 4.2.17 on 2025-05-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0028_remove_salesofmilk_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesofmilk',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.buyer'),
        ),
    ]
