# Generated by Django 4.2.17 on 2025-06-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0030_buyer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='buyer',
            new_name='name',
        ),
    ]
