# Generated by Django 4.2.17 on 2025-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0031_rename_buyer_payments_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='name',
            new_name='buyer',
        ),
    ]
