# Generated by Django 4.2.17 on 2025-06-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0032_rename_name_payments_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='target_group',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Vet Officer')], default='Vet', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.moderator'),
        ),
    ]
