# Generated by Django 4.2.17 on 2025-06-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0033_question_target_group_alter_question_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='category',
            field=models.CharField(choices=[('Neighbour', 'Neighbour'), ('Hotel', 'Hotel'), ('Cooperative', 'Cooperative'), ('Institution', 'Institution')], default='neighbour', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calvingrecord',
            name='days_to_calving_down',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days to calving down', null=True),
        ),
    ]
