# Generated by Django 4.2.17 on 2025-07-18 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0034_payments_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SlaughterhouseHygiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_cleaning', models.DateField()),
                ('cleaning_category', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10)),
                ('cleaning_procedure', models.CharField(choices=[('Floor cleaning', 'Floor cleaning'), ('Wall cleaning', 'Wall cleaning'), ('Manure collection', 'Manure collection'), ('Compound cleaning', 'Compound cleaning'), ('Other', 'Other')], max_length=30)),
                ('state_other_cleaning', models.CharField(blank=True, max_length=100, null=True)),
                ('cleaning_done_by', models.CharField(max_length=100)),
                ('contact_of_cleaner', models.CharField(max_length=20)),
                ('supervised_by', models.CharField(max_length=100)),
                ('supervisor_contact', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaughterhouseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField()),
                ('type_of_asset', models.CharField(choices=[('Land', 'Land'), ('Vehicle', 'Vehicle'), ('Knives', 'Knives'), ('Motorbike', 'Motorbike'), ('Other', 'Other')], max_length=20)),
                ('other_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('original_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appossession_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depossession_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('Chairman', 'Chairman'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer')], max_length=20)),
                ('date_of_enrolment', models.DateField()),
                ('date_of_election', models.DateField()),
                ('time_period', models.CharField(max_length=50)),
                ('next_election_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HidesAndSkinsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_kills', models.DateField()),
                ('category', models.CharField(choices=[('Hides', 'Hides'), ('Skins', 'Skins')], max_length=10)),
                ('number_collected', models.PositiveIntegerField()),
                ('date_of_transportation', models.DateField()),
                ('means_of_transportation', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Motorbike', 'Motorbike')], max_length=10)),
                ('reg_no_of_vehicle', models.CharField(max_length=50)),
                ('taken_by', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedDairyFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_approval', models.DateField()),
                ('name_of_farm', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('name_of_owner', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('farm_breeding_level', models.CharField(max_length=100)),
                ('average_milk_per_cow', models.DecimalField(decimal_places=2, max_digits=6)),
                ('highest_milk_producer', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('CDVS', 'CDVS'), ('DLPO', 'DLPO'), ('Ward Veterinary Officer', 'Ward Veterinary Officer'), ('Ward Production Officer', 'Ward Production Officer')], max_length=50)),
                ('officer_contact', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
