# Generated by Django 4.2.17 on 2025-07-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0035_payment_user_slaughterhousehygiene_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhousehygiene',
            name='date_of_cleaning',
        ),
    ]
