# Generated by Django 4.2.17 on 2025-07-18 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0036_remove_slaughterhousehygiene_date_of_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhousehygiene',
            name='date_of_cleaning',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
