# Generated by Django 4.2.17 on 2025-07-18 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0038_alter_slaughterhouseasset_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveddairyfarm',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
