# Generated by Django 4.2.17 on 2025-07-22 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0039_alter_approveddairyfarm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykill',
            name='assigned_to_farmer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_farmer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills_farmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
