# Generated by Django 4.2.17 on 2025-07-22 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0040_dailykill_assigned_to_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouse',
            name='assigned_to_vet',
            field=models.ForeignKey(default=1, limit_choices_to={'is_vet': True}, on_delete=django.db.models.deletion.CASCADE, related_name='slaughter_house_vet', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
