# Generated by Django 4.2.17 on 2025-07-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0041_slaughterhouse_assigned_to_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_to_vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_vet', to=settings.AUTH_USER_MODEL),
        ),
    ]
