# Generated by Django 4.2.17 on 2025-07-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0042_employee_assigned_to_vet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveddairyfarm',
            name='user',
        ),
    ]
