# Generated by Django 4.2.17 on 2025-08-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0043_remove_approveddairyfarm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livestock_type', models.CharField(choices=[('dairy_cow', 'Dairy Cow'), ('beef', 'Beef'), ('sheep', 'Sheep'), ('goat', 'Goat')], max_length=20)),
                ('date_of_registration', models.DateField()),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('age', models.PositiveIntegerField(help_text='Age in months/years')),
                ('body_weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=6)),
                ('colour', models.CharField(max_length=50)),
                ('number_of_births', models.PositiveIntegerField(default=0)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('breeding_level', models.CharField(blank=True, max_length=100, null=True)),
                ('dam_details', models.CharField(blank=True, max_length=255, null=True)),
                ('sire_details', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(choices=[('kenya', 'Kenya'), ('imported', 'Imported')], max_length=10)),
                ('country_of_importation', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('farm', 'Farm'), ('market', 'Market')], max_length=20)),
                ('farm_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_id_number', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('service_provided_by', models.CharField(max_length=150)),
                ('practitioner_name', models.CharField(max_length=150)),
                ('reg_number', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('signature_and_stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='livestock_photos/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
