# Generated by Django 4.2.17 on 2025-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0045_veterinaryeprescription_routinemanagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abortionrecord',
            name='livestock_category',
            field=models.CharField(choices=[('dairy cow', 'Dairy Cow'), ('beef', 'Beef'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='abortionrecord',
            name='reason_for_abortion',
            field=models.CharField(choices=[('infection', 'Infection'), ('deworming', 'Deworming'), ('injuries', 'Injuries'), ('shock', 'Shock'), ('bull mounting', 'Bull Mounting'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='livestockregistration',
            name='registration_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routinemanagement',
            name='livestock_category',
            field=models.CharField(choices=[('dairy cow', 'Dairy Cow'), ('beef', 'Beef'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routinemanagement',
            name='routine_management',
            field=models.CharField(choices=[('dehorning', 'Dehorning'), ('castration', 'Castration'), ('hoof trimming', 'Hoof Trimming'), ('iron injection', 'Iron Injection'), ('debeaking', 'Debeaking'), ('shearing', 'Shearing'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='buyer_category',
            field=models.CharField(blank=True, choices=[('vet practitioner', 'Vet Practitioner'), ('farmer', 'Farmer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='prescription_target',
            field=models.CharField(blank=True, choices=[('vet practitioner', 'Vet Practitioner'), ('farmer', 'Farmer')], max_length=20),
        ),
    ]
