# Generated by Django 4.2.17 on 2025-08-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0046_alter_abortionrecord_livestock_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='vet_in_charge',
        ),
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='vet_registration_number',
        ),
        migrations.AlterField(
            model_name='emergencycare',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veterinaryeprescription',
            name='livestock_type',
            field=models.CharField(choices=[('dairy cow', 'Dairy Cow'), ('beef', 'Beef'), ('sheep', 'Sheep'), ('goat', 'Goat')], max_length=20),
        ),
    ]
