# Generated by Django 4.2.17 on 2025-09-29 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0047_remove_surgicalrecord_vet_in_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_extension', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('target_group', models.CharField(choices=[('self_help_group', 'Self Help Group'), ('cbo', 'CBO'), ('community', 'Community'), ('institution', 'Institution'), ('field_day', 'Field Day')], max_length=50)),
                ('topic_covered', models.CharField(max_length=255)),
                ('number_of_participants', models.PositiveIntegerField()),
                ('female_attendance', models.PositiveIntegerField(default=0)),
                ('male_attendance', models.PositiveIntegerField(default=0)),
                ('children_attendance', models.PositiveIntegerField(default=0)),
                ('name_of_group', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('group_project', models.CharField(blank=True, choices=[('dairy', 'Dairy'), ('beef', 'Beef'), ('sheep', 'Sheep'), ('goats', 'Goats'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=50, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county', models.CharField(max_length=255)),
                ('chairperson', models.CharField(blank=True, max_length=255, null=True)),
                ('secretary', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer', models.CharField(blank=True, max_length=255, null=True)),
                ('member', models.CharField(blank=True, max_length=255, null=True)),
                ('facilitator_name', models.CharField(max_length=255)),
                ('facilitator_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_token', models.CharField(blank=True, max_length=255, null=True)),
                ('extension_organized_by', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='extension_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
