# Generated by Django 4.2.17 on 2025-11-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0048_extensionservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abortionrecord',
            name='service_provided_by',
        ),
        migrations.RemoveField(
            model_name='artificialinsemination',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='deworming',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='emergencycare',
            name='service_provided_by',
        ),
        migrations.RemoveField(
            model_name='farmconsultation',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='livestockregistration',
            name='service_provided_by',
        ),
        migrations.RemoveField(
            model_name='postmortemrecord',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='pregnancydiagnosis',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='routinemanagement',
            name='service_provided_by',
        ),
        migrations.RemoveField(
            model_name='samplecollection',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='surgicalrecord',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='uterineirrigationrecord',
            name='service_provided_by',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='provided_by',
        ),
        migrations.RemoveField(
            model_name='veterinarybilling',
            name='provided_by',
        ),
    ]
