# Generated by Django 4.2.17 on 2025-11-24 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0049_remove_abortionrecord_service_provided_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_quotation', models.DateField()),
                ('quotation_category', models.CharField(choices=[('deworming', 'Deworming'), ('surgery', 'Surgery'), ('clinical', 'Clinical'), ('ai', 'Artificial Insemination'), ('vaccination', 'Vaccination'), ('post_mortem', 'Post Mortem'), ('pregnancy_diagnosis', 'Pregnancy Diagnosis'), ('lab_charges', 'Lab Charges'), ('farm_consultation', 'Farm Consultation'), ('telemedicine', 'Telemedicine Services'), ('uterine_irrigation', 'Uterine Irrigation'), ('emergency', 'Emergency Care'), ('livestock_exam', 'Livestock Examination'), ('routine_mgmt', 'Routine Management')], max_length=50)),
                ('number_of_animals', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('amount_to_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name_of_farm', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('services_provided_by', models.CharField(blank=True, max_length=255, null=True)),
                ('practitioner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kvb_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('practitioner_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('signature_and_stamp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
