# Generated by Django 4.2.17 on 2025-12-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0051_zoomtoken_zoommeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='zoom_meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.zoommeeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='facilitator',
            field=models.CharField(default='kirui', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='price',
            field=models.DecimalField(decimal_places=2, default='5.0', max_digits=6),
            preserve_default=False,
        ),
    ]
