# Generated by Django 4.2.17 on 2025-12-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0052_payment_zoom_meeting_zoommeeting_facilitator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='zoom_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_payments', to='portals.zoommeeting'),
        ),
        migrations.CreateModel(
            name='ZoomAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='portals.zoommeeting')),
            ],
        ),
    ]
