# Generated by Django 4.2.17 on 2025-12-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0053_alter_payment_zoom_meeting_zoomattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoomattendance',
            old_name='duration_minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='zoomattendance',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='zoomattendance',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='zoomattendance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='zoomattendance',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zoomattendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.zoommeeting'),
        ),
    ]
