# Generated by Django 4.2.17 on 2025-12-10 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0054_rename_duration_minutes_zoomattendance_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomattendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zoomattendance',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoomattendance',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zoomattendance',
            name='user_email',
            field=models.CharField(default='soinvet@mail.com', max_length=255),
            preserve_default=False,
        ),
    ]
