# Generated by Django 4.2.17 on 2025-12-11 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0055_zoomattendance_user_alter_zoomattendance_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cpd_number', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points', models.IntegerField()),
                ('presented_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='cpd_number',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='points',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='presented_by',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.lesson'),
        ),
    ]
