# Generated by Django 4.2.17 on 2025-12-11 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0056_lesson_remove_tutorial_cpd_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='cpd_number',
            field=models.CharField(default='3rh3ih', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='presented_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='lesson',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
