# Generated by Django 4.2.17 on 2025-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0057_tutorial_cpd_number_tutorial_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='contact_hours',
            field=models.CharField(default='3', max_length=100),
            preserve_default=False,
        ),
    ]
