# Generated by Django 4.2.17 on 2025-12-12 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0058_tutorial_contact_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='contact_hours',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.CreateModel(
            name='MilkCollectionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_enrollment', models.DateField()),
                ('name_of_collection_centre', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('agent_incharge', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('approximate_number_of_farmers', models.PositiveIntegerField()),
                ('means_of_transfer', models.CharField(choices=[('Motorbike', 'Motorbike'), ('Vehicle', 'Vehicle'), ('Lorry', 'Lorry')], max_length=20)),
                ('transporter_name', models.CharField(max_length=255)),
                ('transporter_mobile', models.CharField(max_length=20)),
                ('time_of_milk_collection', models.TimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerMilkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField()),
                ('milk_supply_number', models.CharField(max_length=50)),
                ('name_in_full', models.CharField(max_length=255)),
                ('total_milk_supplied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DairyFarmerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('total_number_of_dairy_cows', models.PositiveIntegerField()),
                ('number_of_lactating_cows', models.PositiveIntegerField()),
                ('breeds_used', models.CharField(choices=[('FH', 'Friesian'), ('J', 'Jersey'), ('AY', 'Ayrshire'), ('GU', 'Guernsey'), ('BS', 'Brown Swiss'), ('Other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('milk_supply_number', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMilkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_amendment', models.DateField()),
                ('last_milk_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_milk_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
