# Generated by Django 4.2.17 on 2025-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0059_alter_tutorial_contact_hours_milkcollectioncenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmermilkpayment',
            name='name_in_full',
        ),
        migrations.AlterField(
            model_name='dairyfarmerregistration',
            name='breeds_used',
            field=models.CharField(choices=[('AI', 'AI'), ('Bull', 'Bull')], max_length=20),
        ),
    ]
