# Generated by Django 4.2.17 on 2025-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0060_remove_farmermilkpayment_name_in_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermilkpayment',
            name='name_in_full',
            field=models.CharField(default='kirui', max_length=255),
            preserve_default=False,
        ),
    ]
