# Generated by Django 4.2.17 on 2025-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0063_alter_milkcollectioncenterrecord_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollectioncenterrecord',
            name='collection_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Rejected', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkcollectioncenterrecord',
            name='reason',
            field=models.CharField(default='adulterated', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkcollectioncooler',
            name='collection_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Rejected', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkcollectioncooler',
            name='reason',
            field=models.CharField(default='has water', max_length=100),
            preserve_default=False,
        ),
    ]
