# Generated by Django 4.2.17 on 2025-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0064_milkcollectioncenterrecord_collection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollectioncenterrecord',
            name='reason',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='milkcollectioncooler',
            name='reason',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
