# Generated by Django 4.2.17 on 2025-12-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0066_alter_milkcollectioncenterrecord_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='assigned_to_cooperative',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'is_cooperative': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_cooperative', to=settings.AUTH_USER_MODEL),
        ),
    ]
