# Generated by Django 4.2.17 on 2026-01-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0067_artificialinsemination_assigned_to_cooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialinsemination',
            name='abortion_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='breed_used',
            field=models.CharField(choices=[('Holstein', 'Holstein'), ('Jersey', 'Jersey'), ('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Simmental', 'Simmental'), ('Brahman', 'Brahman'), ('Charolais', 'Charolais'), ('Limousin', 'Limousin'), ('Guernsey', 'Guernsey'), ('Ayrshire', 'Ayrshire'), ('Brown Swiss', 'Brown Swiss'), ('Shorthorn', 'Shorthorn'), ('Other', 'Other')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='bull_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='bull_reg_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='cow_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='dam_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='farm_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='insemination_status',
            field=models.CharField(choices=[('First', 'First'), ('Repeat', 'Repeat')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='no_of_repeats',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='other_breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='other_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='owners_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='rab_status',
            field=models.CharField(blank=True, choices=[('Manual Removal', 'Manual Removal'), ('Natural Expulsion', 'Natural Expulsion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='reg_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='semen_source',
            field=models.CharField(choices=[('KAGRC', 'KAGRC'), ('ADC', 'ADC'), ('CRV', 'CRV'), ('WW Sires', 'WW Sires'), ('Semex Alliance', 'Semex Alliance'), ('Alta Genetic', 'Alta Genetic'), ('CRI', 'CRI'), ('Other', 'Other')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='semen_type',
            field=models.CharField(choices=[('Conventional', 'Conventional'), ('Sexed', 'Sexed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='sire_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='species',
            field=models.CharField(choices=[('Cattle', 'Cattle'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Donkey', 'Donkey'), ('Dog', 'Dog'), ('Horse', 'Horse'), ('Poultry', 'Poultry'), ('Other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='sub_county',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_category',
            field=models.CharField(choices=[('surgeon', 'Surgeon'), ('technologist', 'Technologist'), ('technician', 'Technician')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_reg_no',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='village',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='ward',
            field=models.CharField(default='', max_length=25),
        ),
    ]
