# Generated by Django 4.2.17 on 2026-01-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0068_alter_artificialinsemination_abortion_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('animal_species', models.CharField(max_length=100)),
                ('total_vaccinated', models.PositiveIntegerField()),
                ('vaccine_used', models.CharField(max_length=150)),
                ('vaccine_source', models.CharField(max_length=150)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('revenue_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacc_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaughterHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('private_slaughterhouses', models.PositiveIntegerField()),
                ('county_slaughterhouses', models.PositiveIntegerField()),
                ('employed_inspectors', models.PositiveIntegerField()),
                ('roller_markers', models.PositiveIntegerField()),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slaugh_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('number_employed_by_county', models.PositiveIntegerField()),
                ('number_in_private_practice', models.PositiveIntegerField()),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pracs_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoObjections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('livestock_category', models.CharField(max_length=100)),
                ('number_of_animals', models.PositiveIntegerField()),
                ('cost_of_no_objection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nobs_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovementPermits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('livestock_category', models.CharField(max_length=100)),
                ('total_animals', models.PositiveIntegerField()),
                ('price_per_animal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_leave_request', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('total_annual_leave_days', models.PositiveIntegerField()),
                ('days_of_leave_taken', models.PositiveIntegerField()),
                ('remaining_days', models.PositiveIntegerField()),
                ('reason_for_leave', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Maternity Leave', 'Maternity Leave'), ('Normal Leave', 'Normal Leave')], max_length=50)),
                ('name_of_officer', models.CharField(max_length=150)),
                ('employment_number', models.CharField(max_length=50)),
                ('working_station', models.CharField(max_length=150)),
                ('leave_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leav_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('number_of_extensions_done', models.PositiveIntegerField()),
                ('provider', models.CharField(choices=[('private', 'Private'), ('county', 'County Government'), ('pharma', 'Pharmaceutical Companies'), ('dairy', 'Dairy Cooperatives')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ext', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseReportMov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('livestock_category', models.CharField(max_length=100)),
                ('number_of_reports', models.PositiveIntegerField()),
                ('suspected_disease', models.CharField(max_length=150)),
                ('proposed_intervention', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='des_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRevenueCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('source_of_revenue', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Daily Levies', 'Daily Levies'), ('Movement Permits', 'Movement Permits'), ('A.I', 'Artificial Insemination')], max_length=50)),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyKills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('livestock_category', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('camel', 'Camel'), ('pig', 'Pig')], max_length=20)),
                ('number_of_kills', models.PositiveIntegerField()),
                ('price_per_kill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyk_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtificialInseminations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_record', models.DateField()),
                ('sub_county', models.CharField(max_length=100)),
                ('number_of_cows_served', models.PositiveIntegerField()),
                ('semen_type', models.CharField(choices=[('sexed', 'Sexed'), ('conventional', 'Conventional'), ('ai', 'AI')], max_length=20)),
                ('repeat_cases', models.PositiveIntegerField(default=0)),
                ('revenue_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_to_official', models.ForeignKey(blank=True, limit_choices_to={'is_official': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_official', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
