# Generated by Django 4.2.17 on 2026-01-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0069_vaccinations_slaughterhouses_practitioners_and_more'),
    ]

    operations = [
    ]
