# Generated by Django 4.2.17 on 2026-02-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0070_auto_20260127_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykill',
            name='assigned_to_farmer',
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='animal_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_farmer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='assigned_to_cooperative',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cooperative': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_cooperative', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinseminations',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinseminations',
            name='semen_type',
            field=models.CharField(choices=[('Sexed', 'Sexed'), ('Conventional', 'Conventional'), ('Ai', 'AI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailykills',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailyk_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyrevenuecollection',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyrevenuecollection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseasereportmov',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='des_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseasereportmov',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extensionservices',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ext', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leav_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementpermits',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movementpermits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noobjections',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nobs_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noobjections',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practitioners',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pracs_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slaughterhouses',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slaugh_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccinations',
            name='assigned_to_official',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacc_official', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LessonAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
