# Generated by Django 6.0.3 on 2026-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0072_milkcollectionclerk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollectioncooler',
            name='location',
            field=models.CharField(default='cooler', max_length=100),
            preserve_default=False,
        ),
    ]
