# Generated by Django 6.0.3 on 2026-03-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0073_milkcollectioncooler_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollectionclerk',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_number',
            field=models.CharField(default=3036, max_length=100),
            preserve_default=False,
        ),
    ]
