# Generated by Django 6.0.3 on 2026-03-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0074_milkcollectionclerk_supplier_supplier_supply_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkcollectionclerk',
            name='supplier',
        ),
    ]
