# Generated by Django 6.0.3 on 2026-03-29 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0075_remove_milkcollectionclerk_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldquotation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_farmer': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='rab_status',
            field=models.CharField(blank=True, choices=[('Manual Removal', 'Manual Removal'), ('Natural Expulsion', 'Natural Expulsion'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_contact',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artificialinsemination',
            name='vet_reg_no',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supply_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
