# Generated by Django 4.2.17 on 2025-11-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_to_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
