# Generated by Django 4.2.17 on 2025-11-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_agree_to_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agree_to_privacy',
        ),
    ]
