# Generated by Django 4.2.17 on 2025-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_agree_to_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
