# Generated by Django 4.2.17 on 2025-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(default='SOIN VETERINARY SERVICES', max_length=100),
        ),
    ]
