# Generated by Django 4.2.17 on 2025-12-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyCooperative',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=100)),
                ('cooperative_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
