# Generated by Django 4.2.17 on 2025-12-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_dairycooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cooperative',
            field=models.BooleanField(default=False),
        ),
    ]
