# Generated by Django 4.2.17 on 2025-12-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_cooperative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairycooperative',
            name='cooperative_name',
        ),
        migrations.AddField(
            model_name='user',
            name='cooperative_name',
            field=models.CharField(default='DAIRY COOPERATIVE SERVICES', max_length=100),
        ),
    ]
