# Generated by Django 4.2.17 on 2026-01-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_dairycooperative_cooperative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='user',
            name='farm_name',
            field=models.CharField(default='SOINFARM', max_length=100),
        ),
    ]
